apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  volumeName: test-pv 
  storageClassName: "" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
