apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: calico-cni-cluster

servers: 1
agents: 2

registries:
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://calico-cni-cluster-registry:5000"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
      - arg: "--disable-network-policy"
        nodeFilters:
          - server:*
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
