services:
  registry:
    image: registry:2
    hostname: custom-registry
    container_name: custom-registry
    ports:
      - "5000:5000"
    restart: always
    networks:
      - k3dnet

networks:
  k3dnet:
    external: true
    name: k3d-custom-registry-cluster 