apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-app
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: localhost:5000/nginx:latest
          ports:
            - containerPort: 80
