apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-nginx-cluster
servers: 1
agents: 2
ports:
  - port: 8080:80  
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
